// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYrI5RgEA0E0K0QRCn8jKfquvRMyAkyjY',
    appId: '1:111659889335:web:d9746b4768d8dac0159332',
    messagingSenderId: '111659889335',
    projectId: 'chatapp-b7780',
    authDomain: 'chatapp-b7780.firebaseapp.com',
    storageBucket: 'chatapp-b7780.appspot.com',
    measurementId: 'G-LN2DWQJD15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPNhz0gYyH7Dw8OwWfSo1j4MG2fuk5EJM',
    appId: '1:111659889335:android:72c30b883e3c287e159332',
    messagingSenderId: '111659889335',
    projectId: 'chatapp-b7780',
    storageBucket: 'chatapp-b7780.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQBGb5gNoOeKCC5mJ6oGp0DH-rROudOzI',
    appId: '1:111659889335:ios:97ef236e06c3f209159332',
    messagingSenderId: '111659889335',
    projectId: 'chatapp-b7780',
    storageBucket: 'chatapp-b7780.appspot.com',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQBGb5gNoOeKCC5mJ6oGp0DH-rROudOzI',
    appId: '1:111659889335:ios:97ef236e06c3f209159332',
    messagingSenderId: '111659889335',
    projectId: 'chatapp-b7780',
    storageBucket: 'chatapp-b7780.appspot.com',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYrI5RgEA0E0K0QRCn8jKfquvRMyAkyjY',
    appId: '1:111659889335:web:3dd43ef8ad480268159332',
    messagingSenderId: '111659889335',
    projectId: 'chatapp-b7780',
    authDomain: 'chatapp-b7780.firebaseapp.com',
    storageBucket: 'chatapp-b7780.appspot.com',
    measurementId: 'G-Z84X1YWF63',
  );
}
